### ISSUE TITLE
Differences between Types and Interfaces

### ISSUE THREAD

**Issue by gibbok** [mkosir/typescript-react-style-guide#2]
### Description

Hey @mkosir ,

I hope you're doing well! I wanted to discuss the section "Type Definition." I'm not entirely certain, but I think there might be a small issue with the text.

It currently says:
"Both are nearly equivalent, so to choose one is mostly an arbitrary decision to achieve a consistent codebase."

In my opinion, types offer more flexibility when defining union and intersection types, and for new projects, I think they could be preferable. What do you think?

For more information, you can check out this link:
[Typescript-book on GitHub](https://github.com/gibbok/typescript-book#differences-between-type-and-interface)

If you have any questions or need further clarification, feel free to ask. Thanks for your time! 😊

**Comment by mkosir** [comment]
Hey @gibbok thanks for heads up on differences, I agree types should be preferable over interfaces!
